services:
  spark-config-generator:
    build:
      context: .
      dockerfile: Dockerfile.config
    container_name: spark-config-generator
    env_file:
      - ./.env
    volumes:
      - .:/workspace
    working_dir: /workspace
    networks:
      - ml-infra-network

  spark-master:
    image: blnkoff/spark-master:latest-aws
    container_name: spark-master
    env_file:
      - ./.env
    ports:
      - "${SPARK_MASTER_UI_PORT:-8080}:8080"
      - "${SPARK_MASTER_PORT:-7077}:7077"
    volumes:
      - ./build/workspace:/opt/workspace
      - ./spark-defaults.conf:/usr/bin/spark-3.5.7-bin-hadoop3/conf/spark-defaults.conf:ro
    depends_on:
      - spark-config-generator
    networks:
      - ml-infra-network

  spark-worker:
    image: blnkoff/spark-worker:latest-aws
    container_name: spark-worker
    env_file:
      - ./.env
    environment:
      - SPARK_WORKER_CORES=3
      - SPARK_WORKER_MEMORY=5g
    ports:
      - "${SPARK_WORKER_UI_PORT:-8081}:8081"
    volumes:
      - ./build/workspace:/opt/workspace
      - ./spark-defaults.conf:/usr/bin/spark-3.5.7-bin-hadoop3/conf/spark-defaults.conf:ro
    depends_on:
      - spark-config-generator
      - spark-master
    networks:
      - ml-infra-network
