services:
  spark-master:
    image: blnkoff/spark-master:latest
    container_name: spark-master
    env_file:
      - ./.env
    ports:
      - "${SPARK_MASTER_UI_PORT:-8080}:8080"
      - "${SPARK_MASTER_PORT:-7077}:7077"
    volumes:
      - ./build/workspace:/opt/workspace
    networks:
      - ml-infra-network

  spark-worker-1:
    image: blnkoff/spark-worker:latest
    container_name: spark-worker-1
    env_file:
      - ./.env
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1g
    ports:
      - "${SPARK_WORKER1_UI_PORT:-8081}:8081"
    volumes:
      - ./build/workspace:/opt/workspace
    depends_on:
      - spark-master
    networks:
      - ml-infra-network
        
  spark-worker-2:
    image: blnkoff/spark-worker:latest
    container_name: spark-worker-2
    env_file:
      - ./.env
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1g
    ports:
      - "${SPARK_WORKER2_UI_PORT:-8082}:8081"
    volumes:
      - ./build/workspace:/opt/workspace
    depends_on:
      - spark-master
    networks:
      - ml-infra-network
